window.VOCAB_INDEX = {
  metadata: {
    projectName: "考研英语二词汇故事站",
    basis: [
      "官方范围依据：英语（二）大纲要求考生较熟练地掌握约5500个常用词汇及相关常用词组。",
      "当前项目执行方式：以 source/kaoyan_2025_5500_source.txt 作为完整总词表来源，再用 priority_words.txt 定义重点词前置顺序。"
    ],
    status: "当前页面已按 priority 实词词库重写 Story 001；完整重排词库由 build_vocab_index.js 生成 generated_vocab_index.json。"
  },
  entries: [
    { id: "001", sourceId: "2044", word: "follow", meaning: "跟随" },
    { id: "002", sourceId: "0436", word: "base", meaning: "基础；基地" },
    { id: "003", sourceId: "0822", word: "child", meaning: "孩子" },
    { id: "004", sourceId: "0830", word: "choice", meaning: "选择" },
    { id: "005", sourceId: "1440", word: "direction", meaning: "方向；指令" },
    { id: "006", sourceId: "2755", word: "job", meaning: "工作" },
    { id: "007", sourceId: "0365", word: "author", meaning: "作者" },
    { id: "008", sourceId: "3094", word: "mean", meaning: "意思是；意味着" },
    { id: "009", sourceId: "4825", word: "state", meaning: "陈述；状态" },
    { id: "010", sourceId: "0833", word: "choose", meaning: "选择" },
    { id: "011", sourceId: "2614", word: "information", meaning: "信息" },
    { id: "012", sourceId: "0659", word: "business", meaning: "商业" },
    { id: "013", sourceId: "4237", word: "research", meaning: "研究" },
    { id: "014", sourceId: "3391", word: "number", meaning: "数字；数量" },
    { id: "015", sourceId: "4597", word: "single", meaning: "单一的" },
    { id: "016", sourceId: "3591", word: "paragraph", meaning: "段落" },
    { id: "017", sourceId: "3986", word: "provide", meaning: "提供" },
    { id: "018", sourceId: "1417", word: "different", meaning: "不同的" },
    { id: "019", sourceId: "2847", word: "last", meaning: "持续；最后的" },
    { id: "020", sourceId: "1142", word: "correspond", meaning: "相符合" },
    { id: "021", sourceId: "1623", word: "education", meaning: "教育" },
    { id: "022", sourceId: "2838", word: "language", meaning: "语言" },
    { id: "023", sourceId: "2238", word: "government", meaning: "政府" },
    { id: "024", sourceId: "5032", word: "system", meaning: "系统" },
    { id: "025", sourceId: "0530", word: "blank", meaning: "空白的" },
    { id: "026", sourceId: "4222", word: "report", meaning: "报告" },
    { id: "027", sourceId: "2362", word: "health", meaning: "健康" },
    { id: "028", sourceId: "2843", word: "large", meaning: "大的" },
    { id: "029", sourceId: "1393", word: "develop", meaning: "发展；培养" },
    { id: "030", sourceId: "1582", word: "during", meaning: "在……期间" },
    { id: "031", sourceId: "4429", word: "science", meaning: "科学" },
    { id: "032", sourceId: "0160", word: "allow", meaning: "允许" },
    { id: "033", sourceId: "2884", word: "leave", meaning: "离开" },
    { id: "034", sourceId: "4234", word: "require", meaning: "需要；要求" },
    { id: "035", sourceId: "4826", word: "statement", meaning: "声明；陈述" },
    { id: "036", sourceId: "4678", word: "society", meaning: "社会" },
    { id: "037", sourceId: "5070", word: "technology", meaning: "技术" },
    { id: "038", sourceId: "2286", word: "grow", meaning: "成长；增长" },
    { id: "039", sourceId: "1612", word: "economic", meaning: "经济上的" },
    { id: "040", sourceId: "2871", word: "lead", meaning: "带领" },
    { id: "041", sourceId: "2952", word: "little", meaning: "小的；少的" },
    { id: "042", sourceId: "0867", word: "class", meaning: "班级；课程" },
    { id: "043", sourceId: "1624", word: "effect", meaning: "效果；影响" },
    { id: "044", sourceId: "1003", word: "comprehension", meaning: "理解" },
    { id: "045", sourceId: "5078", word: "tell", meaning: "告诉；讲述" },
    { id: "046", sourceId: "2925", word: "likely", meaning: "很可能的" },
    { id: "047", sourceId: "1170", word: "course", meaning: "课程" },
    { id: "048", sourceId: "0666", word: "buy", meaning: "购买" },
    { id: "049", sourceId: "3439", word: "offer", meaning: "提供" },
    { id: "050", sourceId: "4497", word: "service", meaning: "服务" }
  ]
};
